trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - '*'

variables:
  - name: node_version
    value: '18.x'
  - group: RenderHooks   # precisa existir no Library

stages:
  - stage: Build
    displayName: 'Build & Test'
    jobs:
      - job: BuildJob
        displayName: 'Install / Test'
        pool:
          vmImage: Dafault
        steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: 'Use Node $(node_version)'
          - script: npm ci
            displayName: 'npm ci'
          # - script: npm test
          #   displayName: 'Run tests'
          - script: npm run build
            displayName: 'Build (if any)'
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: drop

  - stage: Deploy_Dev
    displayName: 'Deploy to Staging'
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
    jobs:
      - deployment: DeployStaging
        displayName: 'Trigger Render Staging'
        environment: 'dev'
        pool:
          vmImage: Dafault
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Triggering Render staging deploy..."
                    # usa a variável secreta do variable group
                    curl -X POST "$(RENDER_DEV_HOOK)"
                  displayName: 'Trigger Render Staging Deploy'

  - stage: Deploy_Prod
    displayName: 'Deploy to Production'
    dependsOn: Deploy_Dev
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
    jobs:
      - deployment: DeployProd
        displayName: 'Trigger Render Production'
        environment: 'production'   # aqui entra a aprovação configurada no portal (se houver)
        pool:
          vmImage: Dafault
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Triggering Render production deploy..."
                    curl -X POST "$(RENDER_PROD_HOOK)"
                  displayName: 'Trigger Render Production Deploy'
